# Generated by Django 4.2.2 on 2025-01-30 13:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='زمان ایجاد پاسخ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='created_ad',
            field=models.DateTimeField(auto_now_add=True, default=None, verbose_name='زمان ایجاد سوال'),
            preserve_default=False,
        ),
    ]
