# Generated by Django 4.2.2 on 2025-01-30 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_answer_app', '0002_answer_created_ad_question_created_ad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_ad',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
