# Generated by Django 4.2.2 on 2025-02-12 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0011_alter_doctor_options_and_more'),
        ('question_answer_app', '0003_rename_created_ad_answer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor', verbose_name='درمانگر'),
        ),
    ]
